swagger: '2.0'
info:
  description: 'CONTRATO/API DEL MICROSERVICIO: department-service'
  version: '1.0'
  title: 'CONTRATO/API PARA LA GESTION DE DEPARTAMENTOS'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: cesarricardo_guerra19@hotmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    
host: pe.com.capacitacion
basePath: /departmentservice
schemes:
  - http
  
paths:  
  #####################################################################################################
  ########################################## [DEPARTAMENTOS] ##########################################
  #####################################################################################################

  /post/departamentos:
    post:
      summary: Funcionalidad para [REGISTRAR] una ENTIDAD de tipo Departamento.
      description: Funcionalidad para [REGISTRAR] una ENTIDAD de tipo Departamento.
      operationId: agregarDepartamento
      produces: 
        - application/json
      parameters:
        - name: body
          in: body 
          description: La Entidad del Departamento
          required: true
          schema:
            $ref: '#/definitions/Departamento'
      responses:
        '200':
          description: PROCESO EXITOSO
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
        '400':
          description: ERROR EN EL PROCESO 
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
  
  
  /delete/departamentos/{id}:
    delete:
      summary: Funcionalidad para [ELIMINAR] una ENTIDAD de tipo Departamento.
      description: Funcionalidad para [ELIMINAR] una ENTIDAD de tipo Departamento.
      operationId: eliminarDepartamento
      parameters:
        - name: id
          in: path
          description: El id del Departamento
          required: true
          type: integer 
      responses:
        '200':
          description: PROCESO EXITOSO
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
        '400':
          description: ERROR EN EL PROCESO 
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
 
 
  /get/departamentos:
    get:
      summary: Funcionalidad para [CONSULTAR] una ENTIDAD de tipo Departamento completa.
      description: Funcionalidad para [CONSULTAR] una ENTIDAD de tipo Departamento completa.
      operationId: consultarDepartamentosAll
      responses:
        '200':
          description: PROCESO EXITOSO
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
        '400':
          description: ERROR EN EL PROCESO 
          schema:
            $ref: '#/definitions/ResponseDeplMsg'  
            

  /get/departamentos/{id}:
    get:
      summary: Funcionalidad para [CONSULTAR] una ENTIDAD de tipo Departamento completa por id.
      description: Funcionalidad para [CONSULTAR] una ENTIDAD de tipo Departamento completa por id.
      operationId: consultarDepartamentosPorId
      parameters:
        - name: id
          in: path
          description: El id del Departamento
          required: true
          type: integer 
      responses:
        '200':
          description: PROCESO EXITOSO
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
        '400':
          description: ERROR EN EL PROCESO 
          schema:
            $ref: '#/definitions/ResponseDeplMsg' 


  /get/departamentos-organizacion/{idOrg}:
    get:
      summary: Funcionalidad para [CONSULTAR] una ENTIDAD de tipo Departamento completa por idOrg.
      description: Funcionalidad para [CONSULTAR] una ENTIDAD de tipo Departamento completa por idOrg.
      operationId: consultarDepartamentoPorOrganizacion
      parameters:
        - name: idOrg
          in: path
          description: El id de la Departamento
          required: true
          type: integer 
      responses:
        '200':
          description: PROCESO EXITOSO
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
        '400':
          description: ERROR EN EL PROCESO 
          schema:
            $ref: '#/definitions/ResponseDeplMsg'
            

 #####################################################################################################
 ########################################### [ENTIDADES] #############################################
 ##################################################################################################### 
definitions: 
  Empleado:
    type: object
    required:
      - nombre
      - edad
      - rol 
    properties:
      id:
        type: integer
      nombre:
        type: string
      edad:
        type: integer
      rol:
        type: string
      idDep:
        type: integer
         
  Departamento:
    type: object
    required:
      - nombre
    properties:
      id:
        type: integer
      nombre:
        type: string
      idOrg:
        type: integer
      listaEmpleados:
        type: array
        items:
          $ref: '#/definitions/Empleado'
          
  ResponseDeplMsg:
    type: object
    properties:
      auditoria:
        type: object
        required:
          - ipApp
          - nombreApp
          - usuarioApp
          - codigoApp
          - codigoHttp
          - mensajeApp
        properties:
          ipApp:
            type: string
          nombreApp:
            type: string
          usuarioApp:
            type: string
          codigoApp:
            type: string
          codigoHttp:
            type: string 
          mensajeApp:
            type: string 
      listaDepartamentos:
        type: array
        items:
          $ref: '#/definitions/Departamento'  
 
externalDocs:
  description: Encuentra mas sobre SWAGGER
  url: 'http://swagger.io'

